### ISSUE TITLE
[Icon] Support third-part icon libraries ?

### ISSUE THREAD

**Issue by int64ago** [Pure-UI/pure#40]
Currently, the Icon seems too simple and writing Unicode is horrible.

Like this `<Icon type="heart" />` ? Of course, the Unicode-way is pleased to be kept.

**Comment by nanokind** [comment]
yeah, I planned to support both `<Icon>&#xe629;</Icon>` and `<Icon type="home" />`

Just as you said above, `Unicode` will be kept as an alternative way

If users would like to add their own icons, let's say adding `FontAwesome`

Just write in this way
```html
<Icon iconset="fa" type="heart" />
```

But before writing this, they must include some special classnames in their page
```css
.pure-icon--fa {
  font-family: "FontAwesome";
}
.fa-heart {
  ...
}
```

`Icon` will use these classnames internally

Although not accomplished yet : \

thoughts?
